# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('gmail', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('institute', models.CharField(max_length=10)),
            ],
        ),
    ]
