# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of birth'),
            preserve_default=False,
        ),
    ]
