# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=10)),
            ],
        ),
    ]
